export type EventMapLayer = "sponsors" | "infrastructure" | "routes";

export type SponsorConfidence = "verified" | "needs_review";

export type SponsorPoi = {
  id: string;
  layer: "sponsors";
  name: string;
  shortName: string;
  category: string;
  address: string;
  coordinates: [number, number];
  websiteUrl?: string;
  routeUrl: string;
  logoText: string;
  logoSrc?: string;
  sourceNote: string;
  confidence: SponsorConfidence;
};

export const BAD_BAYERSOIEN_CENTER: [number, number] = [10.9987, 47.6907];

function mapsRouteUrl(address: string) {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;
}

export const SPONSOR_POIS: SponsorPoi[] = [
  {
    id: "radlstall",
    layer: "sponsors",
    name: "2RadStadl Wurmansau",
    shortName: "2RadStadl",
    category: "Radsport & Werkstatt",
    address: "Gschwendt 19, 82435 Bad Bayersoien",
    coordinates: [10.978315, 47.7003845],
    websiteUrl: "https://radlstall.com/",
    routeUrl: mapsRouteUrl("2RadStadl Wurmansau, Gschwendt 19, 82435 Bad Bayersoien"),
    logoText: "RS",
    logoSrc: "/event-map/sponsors/radlstadl-wurmansau.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "metzgerei-joerg",
    layer: "sponsors",
    name: "Metzgerei Joerg",
    shortName: "Joerg",
    category: "Metzgerei",
    address: "Dorfstr. 24, 82435 Bad Bayersoien",
    coordinates: [11.0004522, 47.6884496],
    websiteUrl: "https://metzgerei-joerg.de/",
    routeUrl: mapsRouteUrl("Metzgerei Joerg, Dorfstr. 24, 82435 Bad Bayersoien"),
    logoText: "MJ",
    logoSrc: "/event-map/sponsors/metzgerei-joerg.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse aus oeffentlichen Branchenangaben, bitte gegenpruefen.",
    confidence: "needs_review",
  },
  {
    id: "parkhotel-kletterpark",
    layer: "sponsors",
    name: "Parkhotel am Soier See / Kletterwald",
    shortName: "Kletterwald",
    category: "Freizeit & Hotel",
    address: "Am Kurpark 1, 82435 Bad Bayersoien",
    coordinates: [11.0033065, 47.6948899],
    websiteUrl: "https://www.parkhotel-bayersoien.de/",
    routeUrl: mapsRouteUrl("Am Kurpark 1, 82435 Bad Bayersoien"),
    logoText: "KP",
    logoSrc: "/event-map/sponsors/parkhotel-soier-see.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "kletterwald",
    layer: "sponsors",
    name: "Garmisch-Partenkirchen Kletterwald",
    shortName: "Kletterwald",
    category: "Freizeit",
    address: "Wankbahnstrasse, 82467 Garmisch-Partenkirchen",
    coordinates: [11.1112157, 47.502532],
    routeUrl: mapsRouteUrl("Kletterwald Garmisch-Partenkirchen"),
    logoText: "KW",
    logoSrc: "/event-map/sponsors/kletterwald.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Standort per OSM-Treffer, bitte gegenpruefen.",
    confidence: "needs_review",
  },
  {
    id: "brandmeier",
    layer: "sponsors",
    name: "Brandmeier",
    shortName: "Brandmeier",
    category: "Baeckerei & Konditorei",
    address: "Dorfstr. 40, 82435 Bad Bayersoien",
    coordinates: [10.9943493, 47.6910423],
    routeUrl: mapsRouteUrl("Brandmeier Baeckerei Konditorei, Bad Bayersoien"),
    logoText: "BM",
    logoSrc: "/event-map/sponsors/brandmeier.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Zuordnung/Adresse bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "ammer-loisach-energie",
    layer: "sponsors",
    name: "Ammer-Loisach Energie",
    shortName: "ALE",
    category: "Regionale Energie",
    address: "Alte Ettaler Str. 25, 82496 Oberau",
    coordinates: [11.122674, 47.5582723],
    websiteUrl: "https://www.ammer-loisach-energie.de/",
    routeUrl: mapsRouteUrl("Ammer-Loisach Energie, Alte Ettaler Str. 25, 82496 Oberau"),
    logoText: "AL",
    logoSrc: "/event-map/sponsors/ammer-loisach-energie.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Sitz/Adresse oeffentlich recherchiert.",
    confidence: "needs_review",
  },
  {
    id: "erhard-bau",
    layer: "sponsors",
    name: "Bauunternehmen Josef Erhard",
    shortName: "Erhard Bau",
    category: "Bauunternehmen",
    address: "Raiffeisenstr. 9, 82401 Rottenbuch",
    coordinates: [10.9614851, 47.7333705],
    routeUrl: mapsRouteUrl("Bauunternehmen Josef Erhard, Raiffeisenstr. 9, 82401 Rottenbuch"),
    logoText: "EB",
    logoSrc: "/event-map/sponsors/erhard-bau.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse oeffentlich recherchiert.",
    confidence: "needs_review",
  },
  {
    id: "huber-cars",
    layer: "sponsors",
    name: "Huber Cars",
    shortName: "Huber Cars",
    category: "Camper & Fahrzeuge",
    address: "Dorfstr. 1, 82398 Oderding",
    coordinates: [11.1078503, 47.8164298],
    routeUrl: mapsRouteUrl("Huber Cars, Dorfstr. 1, 82398 Oderding"),
    logoText: "HC",
    logoSrc: "/event-map/sponsors/huber-cars.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "schwarzarbeit",
    layer: "sponsors",
    name: "100% Schwarzarbeit",
    shortName: "Schwarzarbeit",
    category: "Orthopaedieschuhtechnik",
    address: "Bad Bayersoien",
    coordinates: [10.9967, 47.6924],
    routeUrl: mapsRouteUrl("Orthopaedieschuhtechnik Schwarz Bad Bayersoien"),
    logoText: "OS",
    logoSrc: "/event-map/sponsors/schwarzarbeit.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "fischerhaeusl",
    layer: "sponsors",
    name: "Fischerhaeusl Kiosk am See",
    shortName: "Fischerhaeusl",
    category: "Kiosk & Gastronomie",
    address: "Seemplatz 1, 82435 Bad Bayersoien",
    coordinates: [11.0014, 47.6896],
    routeUrl: mapsRouteUrl("Fischerhaeusl Kiosk am See, Seemplatz 1, Bad Bayersoien"),
    logoText: "FH",
    logoSrc: "/event-map/sponsors/fischerhaeusl.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse aus Logo/Ortshinweis abgeleitet, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "stefan-schilhorn",
    layer: "sponsors",
    name: "Baugeschaeft Stefan Schilhorn",
    shortName: "Schilhorn",
    category: "Maurermeister & Bautechnik",
    address: "Bad Bayersoien",
    coordinates: [10.9938, 47.6918],
    routeUrl: mapsRouteUrl("Baugeschaeft Stefan Schilhorn Bad Bayersoien"),
    logoText: "SS",
    logoSrc: "/event-map/sponsors/stefan-schilhorn.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "b-gosa",
    layer: "sponsors",
    name: "B. Gosa",
    shortName: "B. Gosa",
    category: "Fahrzeuge & Maschinen",
    address: "Am Bauhof 4, 82435 Bad Bayersoien",
    coordinates: [10.9952, 47.6877],
    routeUrl: mapsRouteUrl("B. Gosa Am Bauhof 4 Bad Bayersoien"),
    logoText: "BG",
    logoSrc: "/event-map/sponsors/b-gosa.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse aus Logo gelesen, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "franziska-am-see",
    layer: "sponsors",
    name: "Franziska am See",
    shortName: "Franziska",
    category: "Gastronomie",
    address: "Bad Bayersoien",
    coordinates: [11.0022, 47.6909],
    routeUrl: mapsRouteUrl("Franziska am See Bad Bayersoien"),
    logoText: "FS",
    logoSrc: "/event-map/sponsors/franziska-am-see.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "raiffeisenbank-steingaden",
    layer: "sponsors",
    name: "Raiffeisenbank Steingaden eG",
    shortName: "Raiba",
    category: "Bank",
    address: "Steingaden",
    coordinates: [10.8601, 47.7016],
    routeUrl: mapsRouteUrl("Raiffeisenbank Steingaden eG"),
    logoText: "RB",
    logoSrc: "/event-map/sponsors/raiffeisenbank-steingaden.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Standort grob gesetzt, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "gasthof-weisses-ross",
    layer: "sponsors",
    name: "Gasthof zum Weissen Ross",
    shortName: "Weisses Ross",
    category: "Gasthof",
    address: "82435 Bad Bayersoien",
    coordinates: [10.9981, 47.6892],
    routeUrl: mapsRouteUrl("Gasthof zum Weissen Ross Bad Bayersoien"),
    logoText: "WR",
    logoSrc: "/event-map/sponsors/gasthof-weisses-ross.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "zimmerei-greinwald",
    layer: "sponsors",
    name: "Zimmerei Greinwald GmbH",
    shortName: "Greinwald",
    category: "Zimmerei & Holzhausbau",
    address: "Brandstatt 10, 82435 Bad Bayersoien",
    coordinates: [10.9999, 47.6943],
    routeUrl: mapsRouteUrl("Zimmerei Greinwald Brandstatt 10 Bad Bayersoien"),
    logoText: "ZG",
    logoSrc: "/event-map/sponsors/zimmerei-greinwald.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse aus Logo gelesen, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "stein-grafik",
    layer: "sponsors",
    name: "Stein Grafik",
    shortName: "Stein Grafik",
    category: "Grafik & Beschriftung",
    address: "Bad Bayersoien",
    coordinates: [10.9917, 47.6901],
    routeUrl: mapsRouteUrl("Stein Grafik Bad Bayersoien"),
    logoText: "SG",
    logoSrc: "/event-map/sponsors/stein-grafik.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "hagrmonie",
    layer: "sponsors",
    name: "HagrMonie",
    shortName: "HagrMonie",
    category: "Praxis & Gesundheit",
    address: "Dorfstr. 90, 82435 Bad Bayersoien",
    coordinates: [10.9902, 47.6885],
    routeUrl: mapsRouteUrl("HagrMonie Dorfstrasse 90 Bad Bayersoien"),
    logoText: "HM",
    logoSrc: "/event-map/sponsors/hagrmonie.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse aus Logo gelesen, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "johann-neuner",
    layer: "sponsors",
    name: "Johann Neuner GmbH",
    shortName: "Neuner",
    category: "Sanitaer, Heizung & Spenglerei",
    address: "Bad Bayersoien",
    coordinates: [10.9992, 47.6879],
    routeUrl: mapsRouteUrl("Johann Neuner GmbH Bad Bayersoien"),
    logoText: "JN",
    logoSrc: "/event-map/sponsors/johann-neuner.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "rbmedia",
    layer: "sponsors",
    name: "rbmedia",
    shortName: "rbmedia",
    category: "Werbung & Medien",
    address: "Weinstr. 22-24, 86956 Schongau",
    coordinates: [10.8942, 47.8101],
    routeUrl: mapsRouteUrl("rbmedia Weinstr. 22 24 Schongau"),
    logoText: "RB",
    logoSrc: "/event-map/sponsors/rbmedia.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse aus Logo gelesen, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "tt-erdbau-kieswerk",
    layer: "sponsors",
    name: "TT Erdbau Kieswerk",
    shortName: "TT",
    category: "Erdbau & Kieswerk",
    address: "Region Bad Bayersoien",
    coordinates: [10.9878, 47.6931],
    routeUrl: mapsRouteUrl("TT Erdbau Kieswerk Bad Bayersoien"),
    logoText: "TT",
    logoSrc: "/event-map/sponsors/tt-erdbau-kieswerk.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "schuster-sondermaschinenbau",
    layer: "sponsors",
    name: "Schuster Sondermaschinenbau GmbH",
    shortName: "Schuster",
    category: "Sondermaschinenbau",
    address: "Bad Bayersoien",
    coordinates: [10.9973468, 47.689768],
    routeUrl: mapsRouteUrl("Schuster Sondermaschinenbau Bad Bayersoien"),
    logoText: "SB",
    logoSrc: "/event-map/sponsors/schuster-sondermaschinenbau.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "xaver-schauer",
    layer: "sponsors",
    name: "Xaver Schauer",
    shortName: "Schauer",
    category: "Sanitaer, Heizung & Spenglerei",
    address: "Bad Bayersoien",
    coordinates: [10.9928, 47.6889],
    routeUrl: mapsRouteUrl("Xaver Schauer Sanitaer Heizung Spenglerei Bad Bayersoien"),
    logoText: "XS",
    logoSrc: "/event-map/sponsors/xaver-schauer.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "paulaner",
    layer: "sponsors",
    name: "Paulaner",
    shortName: "Paulaner",
    category: "Brauerei",
    address: "Muenchen",
    coordinates: [11.597, 48.124],
    routeUrl: mapsRouteUrl("Paulaner Muenchen"),
    logoText: "PA",
    logoSrc: "/event-map/sponsors/paulaner.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Sponsorstandort grob gesetzt, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "autohaus-hager",
    layer: "sponsors",
    name: "Autohaus Hager",
    shortName: "Hager",
    category: "Autohaus",
    address: "Ammergauer Str. 22, 82442 Saulgrub",
    coordinates: [11.0244, 47.6656],
    routeUrl: mapsRouteUrl("Autohaus Hager, Ammergauer Str. 22, 82442 Saulgrub"),
    logoText: "AH",
    logoSrc: "/event-map/sponsors/autohaus-hager.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse aus Logo gelesen, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "atlantis-sportcenter",
    layer: "sponsors",
    name: "Atlantis Sportcenter",
    shortName: "Atlantis",
    category: "Sportcenter",
    address: "Am Widmannweg 2, 86971 Peiting",
    coordinates: [10.9284, 47.8035],
    routeUrl: mapsRouteUrl("Atlantis Sportcenter Am Widmannweg 2 Peiting"),
    logoText: "AS",
    logoSrc: "/event-map/sponsors/atlantis-sportcenter.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse aus Logo gelesen, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "alpin-fachhandel",
    layer: "sponsors",
    name: "Alpin Fachhandel",
    shortName: "Alpin",
    category: "Fachhandel fuer Handwerk",
    address: "Region Oberland",
    coordinates: [10.9894, 47.6947],
    routeUrl: mapsRouteUrl("Alpin Fachhandel fuer das Handwerk Oberland"),
    logoText: "AF",
    logoSrc: "/event-map/sponsors/alpin-fachhandel.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "familie-pfab",
    layer: "sponsors",
    name: "Familie Pfab",
    shortName: "Pfab",
    category: "Regionaler Sponsor",
    address: "Bad Bayersoien",
    coordinates: [10.9974, 47.6947],
    routeUrl: mapsRouteUrl("Familie Pfab Bad Bayersoien"),
    logoText: "FP",
    logoSrc: "/event-map/sponsors/familie-pfab.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "heinritzi",
    layer: "sponsors",
    name: "Heinritzi",
    shortName: "Heinritzi",
    category: "Fahrzeuge",
    address: "Dorfstr. 5, 82435 Bad Bayersoien",
    coordinates: [10.9888069, 47.6934561],
    routeUrl: mapsRouteUrl("Heinritzi Dorfstr. 5 Bad Bayersoien"),
    logoText: "HE",
    logoSrc: "/event-map/sponsors/heinritzi.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Standort per OSM-Treffer, bitte gegenpruefen.",
    confidence: "needs_review",
  },
  {
    id: "mellis-blumenperle",
    layer: "sponsors",
    name: "Mellis Blumenperle",
    shortName: "Blumenperle",
    category: "Floristik",
    address: "Dorfstr. 7, 82435 Bad Bayersoien",
    coordinates: [10.9892, 47.6931],
    routeUrl: mapsRouteUrl("Mellis Blumenperle Dorfstr. 7 Bad Bayersoien"),
    logoText: "MB",
    logoSrc: "/event-map/sponsors/mellis-blumenperle.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse aus Logo gelesen, bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "gerhauser-haustechnik",
    layer: "sponsors",
    name: "Gerhauser Haustechnik",
    shortName: "Gerhauser",
    category: "Haustechnik",
    address: "Region Bad Bayersoien",
    coordinates: [10.9907, 47.6921],
    routeUrl: mapsRouteUrl("Gerhauser Haustechnik Bad Bayersoien"),
    logoText: "GH",
    logoSrc: "/event-map/sponsors/gerhauser-haustechnik.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "franz-staltmeir",
    layer: "sponsors",
    name: "Franz Staltmeir",
    shortName: "Staltmeir",
    category: "Erdarbeiten & Pflasterarbeiten",
    address: "Region Bad Bayersoien",
    coordinates: [10.9859, 47.6914],
    routeUrl: mapsRouteUrl("Franz Staltmeir Erdarbeiten Baggerbetrieb Pflasterarbeiten"),
    logoText: "FS",
    logoSrc: "/event-map/sponsors/franz-staltmeir.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "onkel-blech",
    layer: "sponsors",
    name: "Onkel Blech",
    shortName: "Onkel Blech",
    category: "Musik & Veranstaltung",
    address: "Region Bad Bayersoien",
    coordinates: [10.9865, 47.6897],
    routeUrl: mapsRouteUrl("Onkel Blech"),
    logoText: "OB",
    logoSrc: "/event-map/sponsors/onkel-blech.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "sportzentrale-papistock",
    layer: "sponsors",
    name: "Sportzentrale Papistock",
    shortName: "Papistock",
    category: "Sportfachhandel",
    address: "Region Oberland",
    coordinates: [10.9914, 47.6957],
    routeUrl: mapsRouteUrl("Sportzentrale Papistock"),
    logoText: "SP",
    logoSrc: "/event-map/sponsors/sportzentrale-papistock.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "buchwieser",
    layer: "sponsors",
    name: "Buchwieser",
    shortName: "Buchwieser",
    category: "Land-, Forst- & Gartentechnik",
    address: "Region Bad Bayersoien",
    coordinates: [10.9949, 47.6955],
    routeUrl: mapsRouteUrl("Buchwieser Land Forst Gartentechnik"),
    logoText: "BU",
    logoSrc: "/event-map/sponsors/buchwieser.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "lachmayr-immobilien",
    layer: "sponsors",
    name: "Lachmayr Immobilien",
    shortName: "Lachmayr",
    category: "Immobilien",
    address: "Region Bad Bayersoien",
    coordinates: [10.9978, 47.696],
    routeUrl: mapsRouteUrl("Lachmayr Immobilien"),
    logoText: "LI",
    logoSrc: "/event-map/sponsors/lachmayr-immobilien.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "elektrotechnik-schwarz",
    layer: "sponsors",
    name: "Elektrotechnik Schwarz",
    shortName: "E-Schwarz",
    category: "Elektrotechnik",
    address: "Region Bad Bayersoien",
    coordinates: [11.0007, 47.6956],
    routeUrl: mapsRouteUrl("Elektrotechnik Schwarz Bad Bayersoien"),
    logoText: "ES",
    logoSrc: "/event-map/sponsors/elektrotechnik-schwarz.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "cross-communication",
    layer: "sponsors",
    name: "Cross Communication",
    shortName: "Cross",
    category: "Kommunikation & Grafik",
    address: "Region Bad Bayersoien",
    coordinates: [11.0031, 47.6948],
    routeUrl: mapsRouteUrl("Cross Communication Xaver Tino"),
    logoText: "CC",
    logoSrc: "/event-map/sponsors/cross-communication.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "schreinerei-saal",
    layer: "sponsors",
    name: "Schreinerei Saal",
    shortName: "Saal",
    category: "Schreinerei",
    address: "Region Bad Bayersoien",
    coordinates: [11.0048, 47.6928],
    routeUrl: mapsRouteUrl("Schreinerei Saal Fenster Tueren Moebel Innenausbau"),
    logoText: "SA",
    logoSrc: "/event-map/sponsors/schreinerei-saal.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "ammertal-bau",
    layer: "sponsors",
    name: "Ammertal Bau GmbH",
    shortName: "Ammertal Bau",
    category: "Bauunternehmen",
    address: "Region Ammertal",
    coordinates: [11.0036, 47.6904],
    routeUrl: mapsRouteUrl("Ammertal Bau GmbH"),
    logoText: "AB",
    logoSrc: "/event-map/sponsors/ammertal-bau.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "holzbau-joerg",
    layer: "sponsors",
    name: "Holzbau Joerg",
    shortName: "Holzbau",
    category: "Holzbau",
    address: "Region Bad Bayersoien",
    coordinates: [11.0021, 47.6887],
    routeUrl: mapsRouteUrl("Holzbau Joerg Bad Bayersoien"),
    logoText: "HJ",
    logoSrc: "/event-map/sponsors/holzbau-joerg.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "autohaus-maier",
    layer: "sponsors",
    name: "Autohaus Maier",
    shortName: "Maier",
    category: "Autohaus",
    address: "Region Bad Bayersoien",
    coordinates: [11.0005, 47.6871],
    routeUrl: mapsRouteUrl("Autohaus Maier Bad Bayersoien"),
    logoText: "AM",
    logoSrc: "/event-map/sponsors/autohaus-maier.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025; genauer Standort bitte pruefen.",
    confidence: "needs_review",
  },
];

export function sponsorsToGeoJson(sponsors: SponsorPoi[]) {
  return {
    type: "FeatureCollection" as const,
    features: sponsors.map((sponsor) => ({
      type: "Feature" as const,
      geometry: {
        type: "Point" as const,
        coordinates: sponsor.coordinates,
      },
      properties: {
        id: sponsor.id,
        name: sponsor.name,
        category: sponsor.category,
        confidence: sponsor.confidence,
      },
    })),
  };
}
