export type EventMapLayer = "sponsors" | "infrastructure" | "routes";

export type SponsorConfidence = "verified" | "needs_review";

export type SponsorPoi = {
  id: string;
  layer: "sponsors";
  name: string;
  shortName: string;
  category: string;
  address: string;
  coordinates: [number, number];
  websiteUrl?: string;
  routeUrl: string;
  logoText: string;
  logoSrc?: string;
  sourceNote: string;
  confidence: SponsorConfidence;
};

export const BAD_BAYERSOIEN_CENTER: [number, number] = [10.9987, 47.6907];

function mapsRouteUrl(address: string) {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;
}

export const SPONSOR_POIS: SponsorPoi[] = [
  {
    id: "radlstall",
    layer: "sponsors",
    name: "2RadStadl Wurmansau",
    shortName: "2RadStadl",
    category: "Radsport & Werkstatt",
    address: "Alte Roemerstr. 15, 82442 Saulgrub-Wurmansau",
    coordinates: [11.028264, 47.6467708],
    websiteUrl: "https://www.2radstadl-wurmansau.de/",
    routeUrl: mapsRouteUrl("2RadStadl Wurmansau, Alte Roemerstr. 15, 82442 Saulgrub"),
    logoText: "RS",
    logoSrc: "/event-map/sponsors/radlstadl-wurmansau.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "metzgerei-joerg",
    layer: "sponsors",
    name: "Metzgerei Jörg",
    shortName: "Jörg",
    category: "Metzgerei",
    address: "Hechenrainerstr. 1, 82449 Uffing",
    coordinates: [11.1505168, 47.7157602],
    websiteUrl: "https://metzgerei-joerg.de/",
    routeUrl: mapsRouteUrl("Metzgerei Jörg, Hechenrainerstr. 1, 82449 Uffing"),
    logoText: "MJ",
    logoSrc: "/event-map/sponsors/metzgerei-joerg.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite öffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "parkhotel-kletterpark",
    layer: "sponsors",
    name: "Parkhotel am Soier See",
    shortName: "Parkhotel",
    category: "Hotel",
    address: "Am Kurpark 1, 82435 Bad Bayersoien",
    coordinates: [11.0033065, 47.6948899],
    websiteUrl: "https://www.parkhotel-bayersoien.de/",
    routeUrl: mapsRouteUrl("Am Kurpark 1, 82435 Bad Bayersoien"),
    logoText: "PH",
    logoSrc: "/event-map/sponsors/parkhotel-soier-see.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "kletterwald",
    layer: "sponsors",
    name: "Garmisch-Partenkirchen Kletterwald",
    shortName: "Kletterwald",
    category: "Freizeit",
    address: "Wankbahnstrasse 3, 82467 Garmisch-Partenkirchen",
    coordinates: [11.1113992, 47.5022127],
    websiteUrl: "https://www.kletterwald-gap.de/",
    routeUrl: mapsRouteUrl("Kletterwald Garmisch-Partenkirchen, Wankbahnstrasse 3, 82467 Garmisch-Partenkirchen"),
    logoText: "KW",
    logoSrc: "/event-map/sponsors/kletterwald.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "brandmeier",
    layer: "sponsors",
    name: "Brandmeier",
    shortName: "Brandmeier",
    category: "Baeckerei & Konditorei",
    address: "Dorfstr. 40, 82435 Bad Bayersoien",
    coordinates: [10.9943493, 47.6910423],
    routeUrl: mapsRouteUrl("Brandmeier Baeckerei Konditorei, Bad Bayersoien"),
    logoText: "BM",
    logoSrc: "/event-map/sponsors/brandmeier.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "ammer-loisach-energie",
    layer: "sponsors",
    name: "Ammer-Loisach Energie",
    shortName: "ALE",
    category: "Regionale Energie",
    address: "Alte Ettaler Str. 25, 82496 Oberau",
    coordinates: [11.122674, 47.5582723],
    websiteUrl: "https://www.ammer-loisach-energie.de/",
    routeUrl: mapsRouteUrl("Ammer-Loisach Energie, Alte Ettaler Str. 25, 82496 Oberau"),
    logoText: "AL",
    logoSrc: "/event-map/sponsors/ammer-loisach-energie.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "erhard-bau",
    layer: "sponsors",
    name: "Bauunternehmen Josef Erhard",
    shortName: "Erhard Bau",
    category: "Bauunternehmen",
    address: "Raiffeisenstr. 9, 82401 Rottenbuch",
    coordinates: [10.9614851, 47.7333705],
    routeUrl: mapsRouteUrl("Bauunternehmen Josef Erhard, Raiffeisenstr. 9, 82401 Rottenbuch"),
    logoText: "EB",
    logoSrc: "/event-map/sponsors/erhard-bau.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "huber-cars",
    layer: "sponsors",
    name: "Huber Cars",
    shortName: "Huber Cars",
    category: "Camper & Fahrzeuge",
    address: "Dorfstr. 1, 82398 Oderding",
    coordinates: [11.1078503, 47.8164298],
    routeUrl: mapsRouteUrl("Huber Cars, Dorfstr. 1, 82398 Oderding"),
    logoText: "HC",
    logoSrc: "/event-map/sponsors/huber-cars.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "schwarzarbeit",
    layer: "sponsors",
    name: "100% Schwarzarbeit",
    shortName: "Schwarzarbeit",
    category: "Orthopaedieschuhtechnik",
    address: "Ludwigstr. 27, 82435 Bad Bayersoien",
    coordinates: [10.9889095, 47.6925957],
    websiteUrl: "https://www.osm-schwarz.de/",
    routeUrl: mapsRouteUrl("Orthopaedieschuhtechnik Schwarz, Ludwigstr. 27, 82435 Bad Bayersoien"),
    logoText: "OS",
    logoSrc: "/event-map/sponsors/schwarzarbeit.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "fischerhaeusl",
    layer: "sponsors",
    name: "Fischerhäusl Kiosk am See",
    shortName: "Fischerhäusl",
    category: "Kiosk & Gastronomie",
    address: "Seeweg 104 1/2, 82435 Bad Bayersoien",
    coordinates: [11.0037098, 47.6886562],
    routeUrl: mapsRouteUrl("Fischerhäusl Kiosk am See, Seeweg 104 1/2, 82435 Bad Bayersoien"),
    logoText: "FH",
    logoSrc: "/event-map/sponsors/fischerhaeusl.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "stefan-schilhorn",
    layer: "sponsors",
    name: "Baugeschaeft Stefan Schilhorn",
    shortName: "Schilhorn",
    category: "Maurermeister & Bautechnik",
    address: "Gschwendt 17, 82435 Bad Bayersoien",
    coordinates: [10.9775764, 47.6994031],
    websiteUrl: "https://www.bauplanung-schilhorn.de/",
    routeUrl: mapsRouteUrl("Baugeschaeft Stefan Schilhorn, Gschwendt 17, 82435 Bad Bayersoien"),
    logoText: "SS",
    logoSrc: "/event-map/sponsors/stefan-schilhorn.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "b-gosa",
    layer: "sponsors",
    name: "B. Gosa",
    shortName: "B. Gosa",
    category: "Fahrzeuge & Maschinen",
    address: "Am Bauhof 4, 82435 Bad Bayersoien",
    coordinates: [10.9976452, 47.6877811],
    routeUrl: mapsRouteUrl("B. Gosa Am Bauhof 4 Bad Bayersoien"),
    logoText: "BG",
    logoSrc: "/event-map/sponsors/b-gosa.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse aus Logo/Geocoding uebernommen.",
    confidence: "needs_review",
  },
  {
    id: "franziska-am-see",
    layer: "sponsors",
    name: "Franziska am See",
    shortName: "Franziska",
    category: "Moorbad & Ferienwohnungen",
    address: "Dorfstr. 81, 82435 Bad Bayersoien",
    coordinates: [11.0009703, 47.6885905],
    websiteUrl: "https://www.moorbad.net/",
    routeUrl: mapsRouteUrl("Franziska am See, Dorfstr. 81, 82435 Bad Bayersoien"),
    logoText: "FS",
    logoSrc: "/event-map/sponsors/franziska-am-see.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "raiffeisenbank-steingaden",
    layer: "sponsors",
    name: "Raiffeisenbank Steingaden eG",
    shortName: "Raiba",
    category: "Bank",
    address: "Fuessener Str. 15, 86989 Steingaden",
    coordinates: [10.8611188, 47.6989363],
    websiteUrl: "https://www.raiba-steingaden.de/",
    routeUrl: mapsRouteUrl("Raiffeisenbank Steingaden eG, Fuessener Str. 15, 86989 Steingaden"),
    logoText: "RB",
    logoSrc: "/event-map/sponsors/raiffeisenbank-steingaden.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Hauptstelle/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "gasthof-weisses-ross",
    layer: "sponsors",
    name: "Gasthof zum Weissen Ross",
    shortName: "Weisses Ross",
    category: "Gasthof",
    address: "Dorfstr. 20, 82435 Bad Bayersoien",
    coordinates: [10.9924533, 47.6921415],
    websiteUrl: "https://www.gasthof-zum-weissenross.de/",
    routeUrl: mapsRouteUrl("Gasthof zum Weissen Ross, Dorfstr. 20, 82435 Bad Bayersoien"),
    logoText: "WR",
    logoSrc: "/event-map/sponsors/gasthof-weisses-ross.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "zimmerei-greinwald",
    layer: "sponsors",
    name: "Zimmerei Greinwald GmbH",
    shortName: "Greinwald",
    category: "Zimmerei & Holzhausbau",
    address: "Brandstatt 10, 82435 Bad Bayersoien",
    coordinates: [10.9949071, 47.6918842],
    websiteUrl: "https://www.zimmerei-greinwald.de/",
    routeUrl: mapsRouteUrl("Zimmerei Greinwald Brandstatt 10 Bad Bayersoien"),
    logoText: "ZG",
    logoSrc: "/event-map/sponsors/zimmerei-greinwald.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "stein-grafik",
    layer: "sponsors",
    name: "Stein Grafik",
    shortName: "Stein Grafik",
    category: "Grafik & Beschriftung",
    address: "Am Bauhof 9, 82435 Bad Bayersoien",
    coordinates: [10.997911, 47.6874327],
    websiteUrl: "https://www.steinundgrafik.de/",
    routeUrl: mapsRouteUrl("Stein Grafik, Am Bauhof 9, 82435 Bad Bayersoien"),
    logoText: "SG",
    logoSrc: "/event-map/sponsors/stein-grafik.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse von Sebastian geliefert und per Geocoding aufgeloest.",
    confidence: "verified",
  },
  {
    id: "hagrmonie",
    layer: "sponsors",
    name: "HaarMonie",
    shortName: "HaarMonie",
    category: "Friseur",
    address: "Dorfstr. 39, 82435 Bad Bayersoien",
    coordinates: [10.9940552, 47.6915153],
    websiteUrl: "https://www.haarmonie-salon.de/",
    routeUrl: mapsRouteUrl("HaarMonie, Dorfstr. 39, 82435 Bad Bayersoien"),
    logoText: "HM",
    logoSrc: "/event-map/sponsors/hagrmonie.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "johann-neuner",
    layer: "sponsors",
    name: "Johann Neuner GmbH",
    shortName: "Neuner",
    category: "Sanitaer, Heizung & Spenglerei",
    address: "Dorfstr. 1, 82442 Saulgrub",
    coordinates: [11.0250673, 47.6690136],
    websiteUrl: "https://www.neuner-gmbh.de/",
    routeUrl: mapsRouteUrl("Johann Neuner GmbH, Dorfstr. 1, 82442 Saulgrub"),
    logoText: "JN",
    logoSrc: "/event-map/sponsors/johann-neuner.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "rbmedia",
    layer: "sponsors",
    name: "rbmedia",
    shortName: "rbmedia",
    category: "Werbung & Medien",
    address: "Weinstr. 22-24, 86956 Schongau",
    coordinates: [10.8961023, 47.8124194],
    websiteUrl: "https://www.rb-media.com/",
    routeUrl: mapsRouteUrl("rbmedia Weinstr. 22 24 Schongau"),
    logoText: "RB",
    logoSrc: "/event-map/sponsors/rbmedia.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "tt-erdbau-kieswerk",
    layer: "sponsors",
    name: "TT Erdbau Kieswerk",
    shortName: "TT",
    category: "Erdbau & Kieswerk",
    address: "Region Bad Bayersoien",
    coordinates: [10.9878, 47.6931],
    routeUrl: mapsRouteUrl("TT Erdbau Kieswerk Bad Bayersoien"),
    logoText: "TT",
    logoSrc: "/event-map/sponsors/tt-erdbau-kieswerk.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; online kein eindeutiger Firmensitz gefunden, Position bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "streif-erdbau",
    layer: "sponsors",
    name: "Streif Erdbau GmbH",
    shortName: "Streif",
    category: "Erdbau",
    address: "Ziegelfeld 1, 82401 Rottenbuch",
    coordinates: [10.9413398, 47.7314597],
    routeUrl: mapsRouteUrl("Streif Erdbau GmbH, Ziegelfeld 1, 82401 Rottenbuch"),
    logoText: "SE",
    sourceNote: "Sponsor von Sebastian nachgemeldet; Adresse per Geocoding aufgeloest, Logo fehlt noch.",
    confidence: "verified",
  },
  {
    id: "schuster-sondermaschinenbau",
    layer: "sponsors",
    name: "Schuster Sondermaschinenbau GmbH",
    shortName: "Schuster",
    category: "Sondermaschinenbau",
    address: "Moosweg 1, 82389 Boebing-Pischlach",
    coordinates: [10.9895, 47.7571],
    websiteUrl: "https://www.schuster-sondermaschinenbau.de/",
    routeUrl: mapsRouteUrl("Schuster Sondermaschinenbau GmbH, Moosweg 1, 82389 Boebing"),
    logoText: "SB",
    logoSrc: "/event-map/sponsors/schuster-sondermaschinenbau.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "xaver-schauer",
    layer: "sponsors",
    name: "Xaver Schauer",
    shortName: "Schauer",
    category: "Sanitaer, Heizung & Spenglerei",
    address: "Schmiedgasse 4, 82433 Bad Kohlgrub",
    coordinates: [11.0536941, 47.6671204],
    websiteUrl: "https://www.xaverschauer.de/",
    routeUrl: mapsRouteUrl("Xaver Schauer, Schmiedgasse 4, 82433 Bad Kohlgrub"),
    logoText: "XS",
    logoSrc: "/event-map/sponsors/xaver-schauer.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "paulaner",
    layer: "sponsors",
    name: "Paulaner",
    shortName: "Paulaner",
    category: "Brauerei",
    address: "Ohlmuellerstr. 42, 81541 Muenchen",
    coordinates: [11.5815549, 48.1232953],
    websiteUrl: "https://www.paulaner-gruppe.de/",
    routeUrl: mapsRouteUrl("Paulaner Brauerei Gruppe, Ohlmuellerstr. 42, 81541 Muenchen"),
    logoText: "PA",
    logoSrc: "/event-map/sponsors/paulaner.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Firmensitz oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "autohaus-hager",
    layer: "sponsors",
    name: "Autohaus Hager",
    shortName: "Hager",
    category: "Autohaus",
    address: "Ammergauer Str. 22-24, 82442 Saulgrub",
    coordinates: [11.0242985, 47.6653232],
    websiteUrl: "https://www.toyota-hager.de/",
    routeUrl: mapsRouteUrl("Autohaus Hager, Ammergauer Str. 22-24, 82442 Saulgrub"),
    logoText: "AH",
    logoSrc: "/event-map/sponsors/autohaus-hager.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "atlantis-sportcenter",
    layer: "sponsors",
    name: "Atlantis Sportcenter",
    shortName: "Atlantis",
    category: "Sportcenter",
    address: "Am Widmannweg 2, 86971 Peiting",
    coordinates: [10.9367449, 47.8046174],
    websiteUrl: "https://atlantis-sportcenter.de/",
    routeUrl: mapsRouteUrl("Atlantis Sportcenter, Am Widmannweg 2, 86971 Peiting"),
    logoText: "AS",
    logoSrc: "/event-map/sponsors/atlantis-sportcenter.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "alpin-fachhandel",
    layer: "sponsors",
    name: "Alpin Baustoffhandel und Transport",
    shortName: "Alpin",
    category: "Fachhandel fuer Handwerk",
    address: "Sommerhof 6, 82435 Bad Bayersoien",
    coordinates: [10.9801241, 47.7088416],
    websiteUrl: "https://shop-alpin-baustoffe.com/",
    routeUrl: mapsRouteUrl("Alpin Baustoffhandel, Sommerhof 6, 82435 Bad Bayersoien"),
    logoText: "AF",
    logoSrc: "/event-map/sponsors/alpin-fachhandel.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "familie-pfab",
    layer: "sponsors",
    name: "Familie Pfab",
    shortName: "Pfab",
    category: "Regionaler Sponsor",
    address: "Dorfstr. 35, 82435 Bad Bayersoien",
    coordinates: [10.993527, 47.6919862],
    routeUrl: mapsRouteUrl("Familie Pfab, Dorfstr. 35, 82435 Bad Bayersoien"),
    logoText: "FP",
    logoSrc: "/event-map/sponsors/familie-pfab.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse von Sebastian geliefert und per Geocoding aufgeloest.",
    confidence: "verified",
  },
  {
    id: "heinritzi",
    layer: "sponsors",
    name: "Heinritzi",
    shortName: "Heinritzi",
    category: "Tankstelle & Autohaus",
    address: "Dorfstr. 5, 82435 Bad Bayersoien",
    coordinates: [10.98924, 47.6934561],
    routeUrl: mapsRouteUrl("Heinritzi Dorfstr. 5 Bad Bayersoien"),
    logoText: "HE",
    logoSrc: "/event-map/sponsors/heinritzi.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse bestaetigt, Marker leicht oestlich versetzt damit er nicht mit Mellis Blumenperle kollidiert.",
    confidence: "verified",
  },
  {
    id: "mellis-blumenperle",
    layer: "sponsors",
    name: "Mellis Blumenperle",
    shortName: "Blumenperle",
    category: "Floristik",
    address: "Dorfstr. 7, 82435 Bad Bayersoien",
    coordinates: [10.9888069, 47.6934561],
    routeUrl: mapsRouteUrl("Mellis Blumenperle Dorfstr. 7 Bad Bayersoien"),
    logoText: "MB",
    logoSrc: "/event-map/sponsors/mellis-blumenperle.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; Adresse oeffentlich recherchiert, eigene Webseite nicht gefunden.",
    confidence: "needs_review",
  },
  {
    id: "gerhauser-haustechnik",
    layer: "sponsors",
    name: "Gerhauser Haustechnik",
    shortName: "Gerhauser",
    category: "Haustechnik",
    address: "Am Muehlbach 11, 82442 Saulgrub",
    coordinates: [11.0263961, 47.6671771],
    websiteUrl: "https://www.gerhauser-haustechnik.de/",
    routeUrl: mapsRouteUrl("Gerhauser Haustechnik, Am Muehlbach 11, 82442 Saulgrub"),
    logoText: "GH",
    logoSrc: "/event-map/sponsors/gerhauser-haustechnik.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "franz-staltmeir",
    layer: "sponsors",
    name: "Franz Staltmeir",
    shortName: "Staltmeir",
    category: "Erdarbeiten & Pflasterarbeiten",
    address: "Wurmansauer Str. 18, 82442 Saulgrub-Altenau",
    coordinates: [11.0187338, 47.6480246],
    websiteUrl: "https://www.bagger-franz.de/",
    routeUrl: mapsRouteUrl("Franz Staltmeir Erdarbeiten, Wurmansauer Str. 18, 82442 Saulgrub"),
    logoText: "FS",
    logoSrc: "/event-map/sponsors/franz-staltmeir.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "onkel-blech",
    layer: "sponsors",
    name: "Ömer Blech",
    shortName: "Ömer Blech",
    category: "Musik & Veranstaltung",
    address: "Region Bad Bayersoien",
    coordinates: [10.9865, 47.6897],
    routeUrl: mapsRouteUrl("Ömer Blech"),
    logoText: "ÖB",
    logoSrc: "/event-map/sponsors/onkel-blech.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025; online kein eindeutiger Firmensitz gefunden, Position bitte pruefen.",
    confidence: "needs_review",
  },
  {
    id: "sportzentrale-papistock",
    layer: "sponsors",
    name: "Sportzentrale Papistock",
    shortName: "Papistock",
    category: "Sportfachhandel",
    address: "Bahnhofstr. 6a, 82487 Oberammergau",
    coordinates: [11.0584801, 47.5985995],
    websiteUrl: "https://www.sportzentrale-papistock.de/",
    routeUrl: mapsRouteUrl("Sportzentrale Papistock, Bahnhofstr. 6a, 82487 Oberammergau"),
    logoText: "SP",
    logoSrc: "/event-map/sponsors/sportzentrale-papistock.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "buchwieser",
    layer: "sponsors",
    name: "Buchwieser",
    shortName: "Buchwieser",
    category: "Land-, Forst- & Gartentechnik",
    address: "Martin-Schweiger-Str. 7, 82497 Unterammergau",
    coordinates: [11.0265828, 47.6168771],
    websiteUrl: "https://buchwieser-landtechnik.de/",
    routeUrl: mapsRouteUrl("Buchwieser Landtechnik, Martin-Schweiger-Str. 7, 82497 Unterammergau"),
    logoText: "BU",
    logoSrc: "/event-map/sponsors/buchwieser.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "lachmayr-immobilien",
    layer: "sponsors",
    name: "Lachmayr Immobilien",
    shortName: "Lachmayr",
    category: "Immobilien",
    address: "Reichelstr. 2, 86956 Schongau",
    coordinates: [10.8963908, 47.8138397],
    websiteUrl: "https://www.lachmayr-immobilien.de/",
    routeUrl: mapsRouteUrl("Lachmayr Immobilien, Reichelstr. 2, 86956 Schongau"),
    logoText: "LI",
    logoSrc: "/event-map/sponsors/lachmayr-immobilien.webp",
    sourceNote: "Flyer-Logo aus der Ausschreibung 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "elektrotechnik-schwarz",
    layer: "sponsors",
    name: "Elektrotechnik Schwarz",
    shortName: "E-Schwarz",
    category: "Elektrotechnik",
    address: "Dorfstr. 38, 82435 Bad Bayersoien",
    coordinates: [10.994113, 47.6911203],
    websiteUrl: "https://www.schwarz-elektrotechnik.com/",
    routeUrl: mapsRouteUrl("Elektrotechnik Schwarz, Dorfstr. 38, 82435 Bad Bayersoien"),
    logoText: "ES",
    logoSrc: "/event-map/sponsors/elektrotechnik-schwarz.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "cross-communication",
    layer: "sponsors",
    name: "Cross Communication",
    shortName: "Cross",
    category: "Kommunikation & Grafik",
    address: "Dorfstr. 74, 82435 Bad Bayersoien",
    coordinates: [10.9989315, 47.6887656],
    routeUrl: mapsRouteUrl("Cross Communication, Dorfstr. 74, 82435 Bad Bayersoien"),
    logoText: "CC",
    logoSrc: "/event-map/sponsors/cross-communication.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025; Adresse von Sebastian geliefert und per Geocoding aufgeloest.",
    confidence: "verified",
  },
  {
    id: "schreinerei-saal",
    layer: "sponsors",
    name: "Schreinerei Saal",
    shortName: "Saal",
    category: "Schreinerei",
    address: "Dorfstr. 33, 82435 Bad Bayersoien",
    coordinates: [10.9933423, 47.6921404],
    websiteUrl: "https://www.schreinerei-saal.de/",
    routeUrl: mapsRouteUrl("Schreinerei Saal, Dorfstr. 33, 82435 Bad Bayersoien"),
    logoText: "SA",
    logoSrc: "/event-map/sponsors/schreinerei-saal.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "ammertal-bau",
    layer: "sponsors",
    name: "Ammertal Bau GmbH",
    shortName: "Ammertal Bau",
    category: "Bauunternehmen",
    address: "Saulgruber Str. 11, 82442 Saulgrub-Altenau",
    coordinates: [11.0150735, 47.6510707],
    websiteUrl: "https://www.ammertalbau.com/",
    routeUrl: mapsRouteUrl("Ammertal Bau GmbH, Saulgruber Str. 11, 82442 Saulgrub"),
    logoText: "AB",
    logoSrc: "/event-map/sponsors/ammertal-bau.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "holzbau-joerg",
    layer: "sponsors",
    name: "Holzbau Joerg",
    shortName: "Holzbau",
    category: "Holzbau",
    address: "Soiermuehlweg 3, 82435 Bad Bayersoien",
    coordinates: [10.9873511, 47.6918255],
    websiteUrl: "https://www.holzbau-joerg.com/",
    routeUrl: mapsRouteUrl("Holzbau Joerg, Soiermuehlweg 3, 82435 Bad Bayersoien"),
    logoText: "HJ",
    logoSrc: "/event-map/sponsors/holzbau-joerg.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
  {
    id: "autohaus-maier",
    layer: "sponsors",
    name: "Autohaus Maier",
    shortName: "Maier",
    category: "Autohaus",
    address: "Ammergauer Str. 34, 82442 Saulgrub",
    coordinates: [11.025091, 47.6633867],
    websiteUrl: "https://ahmaier.de/",
    routeUrl: mapsRouteUrl("Autohaus Maier, Ammergauer Str. 34, 82442 Saulgrub"),
    logoText: "AM",
    logoSrc: "/event-map/sponsors/autohaus-maier.webp",
    sourceNote: "Flyer-Logo aus der Rueckseite 2025, Adresse/Webseite oeffentlich recherchiert.",
    confidence: "verified",
  },
];

export function sponsorsToGeoJson(sponsors: SponsorPoi[]) {
  return {
    type: "FeatureCollection" as const,
    features: sponsors.map((sponsor) => ({
      type: "Feature" as const,
      geometry: {
        type: "Point" as const,
        coordinates: sponsor.coordinates,
      },
      properties: {
        id: sponsor.id,
        name: sponsor.name,
        category: sponsor.category,
        confidence: sponsor.confidence,
      },
    })),
  };
}
